vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
       products:
           uri_prefix: /uploads/photos
           upload_destination: '%kernel.project_dir%/public/uploads/photos'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
