vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
       equipement_photos:
           uri_prefix: '%equipement_photos%'
           upload_destination: '%kernel.project_dir%/public%equipement_photos%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
